### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by noamgat** [autonomousvision/occupancy_networks#10]
Hi,
I'm trying to get this project to run on windows.
I managed to compile the extensions (Without dmc). When I run the sample command

`python generate.py configs/demo.yaml`

I get the following error:

`Traceback (most recent call last):
  File "generate.py", line 145, in <module>
    out = generator.generate_mesh(data)
  File "D:\Programming\Projects\MSc\details\occupancy_networks\im2mesh\onet\generation.py", line 81, in generate_mesh
    mesh = self.generate_from_latent(z, c, stats_dict=stats_dict, **kwargs)
  File "D:\Programming\Projects\MSc\details\occupancy_networks\im2mesh\onet\generation.py", line 114, in generate_from_latent
    points = mesh_extractor.query()
  File "im2mesh\utils\libmise\mise.pyx", line 122, in im2mesh.utils.libmise.mise.MISE.query
    cdef long[:, :] points_view = points_np
ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'`

Any idea how to tackle this? (Windows 10, 64 bit)

**Comment by LMescheder** [comment]
Hi @noamgat,
we haven't tested the repository on Windows and we are not planning to support it in the future. If you want to work under Windows, I recommend that you try the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) and perhaps a Docker container. If you choose the latter path, please also consider contributing the working Docker definition file to the main repository. Thanks!

**Comment by noamgat** [comment]
Which systems have you tested on? MacOS? Linux?

**Comment by LMescheder** [comment]
@noamgat We tested our code on Ubuntu 16.04 and Ubuntu 18.04.

**Comment by rozentill** [comment]
I made it work on Windows, just change the type np.int64 to np.long or other types that not be treated as long long. There could also be other ways to solve this.

**Comment by fashionguy** [comment]
@rozentill I get the error. I don't know how to change the type and which variable should be changed. Do you remember sitll?
![image](https://user-images.githubusercontent.com/49114843/81937979-deda6600-9626-11ea-9bb5-a7fd397a59ff.png)

**Comment by pangyyyyy** [comment]
Hi @fashionguy - not sure if you still need it, I changed  `np.int64` to `np.long` in lines 122 and 167 of the `mise.pyx` script. To rebuild it, delete any existing `lib.win-amd64-3.6` files under the build folder and re-compile it `python setup.py build_ext --inplace`. This worked for me on windows following @rozentill's method

**Comment by morankim** [comment]
I fixed setup.py like this
 
![image](https://github.com/autonomousvision/occupancy_networks/assets/15083315/1b2642db-4612-4b69-bc5b-75c4fb9a8c10)
![image](https://github.com/autonomousvision/occupancy_networks/assets/15083315/dfbbf98a-3239-490c-b953-48ceca4f205c)
![image](https://github.com/autonomousvision/occupancy_networks/assets/15083315/d42fad0a-df25-4199-bf76-c25e3fa5f2b8)

and erased dmc import like image 
![image](https://github.com/autonomousvision/occupancy_networks/assets/15083315/cbdea23c-3150-4ae9-acde-c53d3469c525)

then you will build it successfully on Windows.
