### ISSUE TITLE
time

### ISSUE THREAD

**Issue by xiayizhan2017** [autonomousvision/occupancy_networks#11]
hi,
when i run the demo,
Timings[s]:
   mesh time(encode inputs)  time(eval points)  time(marching cubes)  time(refine)  time(simplify)
class name   
n/a                8.02325     0.015601      1.29366     1.439129     4.992291      0.249395
mean            8.02325     0.015601      1.29366     1.439129     4.992291      0.249395
There is  'The inference time of our algorithm with simplification and refinement steps is about 3s / mesh' in the paper.
My GPU is  TITAN Xp, and I don't know why it takes so much time.
Thanks in advance!

**Comment by LMescheder** [comment]
Hi @xiayizhan2017,
this might be related to your hardware (number of CPUs, memory, etc.). You can speed up inference by deactivating the refinement steps in the config. In most cases, the results without refinement are already quite good and refinement only has to fix some remaining problems (e.g. the wings for the airplanes). 

For references, these are my timings:

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>mesh</th>
      <th>time (encode inputs)</th>
      <th>time (eval points)</th>
      <th>time (marching cubes)</th>
      <th>time (refine)</th>
      <th>time (simplify)</th>
    </tr>
    <tr>
      <th>class name</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>airplane,aeroplane,plane</th>
      <td>2.476421</td>
      <td>0.004356</td>
      <td>0.185622</td>
      <td>0.286012</td>
      <td>1.973629</td>
      <td>0.020001</td>
    </tr>
    <tr>
      <th>bench</th>
      <td>2.604014</td>
      <td>0.004670</td>
      <td>0.275009</td>
      <td>0.290625</td>
      <td>1.975990</td>
      <td>0.046294</td>
    </tr>
    <tr>
      <th>cabinet</th>
      <td>2.701229</td>
      <td>0.004617</td>
      <td>0.361059</td>
      <td>0.275236</td>
      <td>1.958236</td>
      <td>0.085722</td>
    </tr>
    <tr>
      <th>car,auto,automobile,machine,motorcar</th>
      <td>2.517779</td>
      <td>0.004301</td>
      <td>0.233938</td>
      <td>0.258221</td>
      <td>1.968386</td>
      <td>0.042734</td>
    </tr>
    <tr>
      <th>chair</th>
      <td>2.748108</td>
      <td>0.004604</td>
      <td>0.403309</td>
      <td>0.259985</td>
      <td>1.972186</td>
      <td>0.092507</td>
    </tr>
    <tr>
      <th>display,video display</th>
      <td>2.692285</td>
      <td>0.004752</td>
      <td>0.335654</td>
      <td>0.289729</td>
      <td>1.974845</td>
      <td>0.072015</td>
    </tr>
    <tr>
      <th>lamp</th>
      <td>2.485771</td>
      <td>0.004298</td>
      <td>0.231635</td>
      <td>0.284154</td>
      <td>1.922944</td>
      <td>0.041966</td>
    </tr>
    <tr>
      <th>loudspeaker,speaker,speaker unit,loudspeaker system,speaker system</th>
      <td>2.869564</td>
      <td>0.004551</td>
      <td>0.493983</td>
      <td>0.284767</td>
      <td>1.953432</td>
      <td>0.113080</td>
    </tr>
    <tr>
      <th>rifle</th>
      <td>2.414753</td>
      <td>0.004707</td>
      <td>0.130775</td>
      <td>0.296746</td>
      <td>1.966976</td>
      <td>0.009909</td>
    </tr>
    <tr>
      <th>sofa,couch,lounge</th>
      <td>2.607800</td>
      <td>0.004229</td>
      <td>0.304244</td>
      <td>0.258011</td>
      <td>1.964742</td>
      <td>0.063347</td>
    </tr>
    <tr>
      <th>table</th>
      <td>2.776753</td>
      <td>0.004727</td>
      <td>0.427196</td>
      <td>0.282940</td>
      <td>1.961718</td>
      <td>0.084139</td>
    </tr>
    <tr>
      <th>telephone,phone,telephone set</th>
      <td>2.518772</td>
      <td>0.004449</td>
      <td>0.214532</td>
      <td>0.280802</td>
      <td>1.970168</td>
      <td>0.038571</td>
    </tr>
    <tr>
      <th>vessel,watercraft</th>
      <td>2.467528</td>
      <td>0.004449</td>
      <td>0.171889</td>
      <td>0.291079</td>
      <td>1.969049</td>
      <td>0.023563</td>
    </tr>
  </tbody>
</table>

**Comment by xiayizhan2017** [comment]
Thanks you for your reply!

**Comment by dahliau** [comment]
Hi,
I wonder, do you know (remember?) the speedup of using the subdivide procedure? 

I'll explain my question:
Are these results are for resolution=256**3?
If so, what is the time difference between eval all 256**3 points vs only points that are inside mark voxels?
Thanks in advance!
