### ISSUE TITLE
ModuleNotFoundError: No module named 'im2mesh.utils.libvoxelize.voxelize'

### ISSUE THREAD

**Issue by alexfrom0815** [autonomousvision/occupancy_networks#111]
'''
../data/external/ShapeNetCore.v1/02691156
../data/ShapeNet.build/02691156
Scaling meshes
Create depths maps
Produce watertight meshes
Process watertight meshes
Traceback (most recent call last):
  File "sample_mesh.py", line 11, in <module>
    from im2mesh.utils import binvox_rw, voxels
  File "../im2mesh/utils/voxels.py", line 6, in <module>
    from im2mesh.utils.libvoxelize.voxelize import voxelize_mesh_
ModuleNotFoundError: No module named 'im2mesh.utils.libvoxelize.voxelize'
'''

Hello, when I use the ‘build.sh’ script to process my own data, it has the above error, which seems to be caused by cython. I can't determine the specific reason and the solution, can you help me? Thanks in advance!

**Comment by Mdemerdash** [comment]
Hi @alexfrom0815 , can you tell me how did you solve this issue?

**Comment by alexfrom0815** [comment]
> Hi @alexfrom0815 , can you tell me how did you solve this issue?

I forgot to run 'python setup.py build_ext --inplace' at first. After that, my problem is solved.

**Comment by Mdemerdash** [comment]
@alexfrom0815 thank you much
