### ISSUE TITLE
Download dataset

### ISSUE THREAD

**Issue by shengjun-zhang** [autonomousvision/occupancy_networks#112]
Hello. When I try to download the dataset through `https://s3.eu-central-1.amazonaws.com/avg-projects/occupancy_networks/data/dataset_small_v1.1.zip`, it appears that the zip file is only 68.4GB. When I unpack it, there are some issue about the dataset.  And I cannot find the gt mesh file in the zip file. So I wonder if it is due to the downloading problem and whether the dataset contains the gt mesh file.

**Comment by machengcheng2016** [comment]
Hi there! Have you found the solution?
