### ISSUE TITLE
My program is running smoothly, but the generated.off file is empty

### ISSUE THREAD

**Issue by hahahahahahahap** [autonomousvision/occupancy_networks#129]
run  `python generate.py configs/demo.yaml`
It looks like it worked

https://s3.eu-central-1.amazonaws.com/avg-projects/occupancy_networks/models/onet_img2mesh_3-f786b04a.pt
=> Loading checkpoint from url...
Warning: generator does not support pointcloud generation.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:01<00:00,  5.77it/s]
Timings [s]:
                mesh  time (encode inputs)  time (eval points)  time (marching cubes)
class name                                                                           
n/a         0.168913              0.001427            0.034569               0.131687
mean        0.168913              0.001427            0.034569               0.131687

It does generate the.off file, but there's nothing in the.off file.

**Comment by hahahahahahahap** [comment]
pytorch 1.0.0 
 cudatoolkit 10.0.130
 torchvision 0.2.0 
 and OS  is Ubuntu 22.04.1
Thank you in advance for your help.

**Comment by Nkcemeka** [comment]
@hahahahahahahap I had the same issue. Have you been able to fix this?

@LMescheder Can you help with this? That will be highly appreciated.

**Comment by hahahahahahahap** [comment]
> @hahahahahahahap I had the same issue. Have you been able to fix this?
> 
> @LMescheder Can you help with this? That will be highly appreciated.

You can try running this code with the CPU, which will solve the problem temporarily.

The main issue is probably that my graphics card version does not support the low version of cuda. I have a 3070 graphics card that does not support cuda 10 version.

**Comment by hahahahahahahap** [comment]
you can change the  [code](https://github.com/autonomousvision/occupancy_networks/blob/406f79468fb8b57b3e76816aaa73b1915c53ad22/generate.py#L26) with  `device = torch.device("cpu")`.

But you know this might not be a good idea. You need to find the right version of cuda for your graphics card as well as pytorch and torchvision... Version of.

**Comment by Nkcemeka** [comment]
Okay, thanks. I will give that a shot. 

I am using a NVIDIA GeForce RTX 4090 with CUDA 12.2. I did have issues and so created a container with CUDA 10. This allowed me get certain things working until I encountered what you experienced. 

I will go ahead to use the cpu instead. 

Thanks.

**Comment by Nkcemeka** [comment]
@hahahahahahahap  Thanks again. By the way, I just tried it and it worked. I don't know if you have tried training, but if you did, I presume you set the device to cpu. I am not sure I really grab how all these GPU architectures work. Shouldn't recent graphic cards be backward compatible with old CUDA versions? I thought with a separate CUDA toolkit in a Docker container, I could get everything to work without problems. Now, I am lost as to what step to take.

**Comment by hahahahahahahap** [comment]
> @hahahahahahahap Thanks again. By the way, I just tried it and it worked. I don't know if you have tried training, but if you did, I presume you set the device to cpu. I am not sure I really grab how all these GPU architectures work. Shouldn't recent graphic cards be backward compatible with old CUDA versions? I thought with a separate CUDA toolkit in a Docker container, I could get everything to work without problems. Now, I am lost as to what step to take.

My guess is that a higher cuda version (which must be supported by your graphics card's computing power) and a suitable pytroch version will make it work.

I didn't do any further research on this network, and yes, I didn't try to train it, which required plenty of time and hard disk space.

I found a replacement, and I thought this [repository ](https://github.com/autonomousvision/convolutional_occupancy_networks)might help you with your current research.

**Comment by Nkcemeka** [comment]
@hahahahahahahap  Thanks a lot. I will check it out.
