### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by xiayizhan2017** [autonomousvision/occupancy_networks#13]
hi,
I preprocessed the data set according to your instructions, but found that some of the samples after processing had no point cloud. 
It is found that the original data set of shapenet is missing point cloud itself. How do you deal with these errors? Did you remove them directly from the train.1st file?
Thanks in advance!

**Comment by LMescheder** [comment]
This is strange. Maybe an error occurred during preprocessing? I think the training code should automatically skip empty examples.

**Comment by xiayizhan2017** [comment]
Thank!
