### ISSUE TITLE
Pixel2mesh training loss plateaus

### ISSUE THREAD

**Issue by simofoti** [autonomousvision/occupancy_networks#16]
Hello,

First of all, thanks for your amazing work! 
I am currently trying to train your pixel2mesh implementation, but I am not able to obtain decent results and I was wondering if you changed something that is not tunable from its config file. 

The code I am using doesn't have any modification and I downloaded your pre-processed data. After epoch 8 the loss plateaus around 30 and oscillates around that value at least until epoch 50 (then I stopped the training because didn't look like it was going to get better).

Here you can find the visualisation of a prediction and its GT at epoch 50.

![000](https://user-images.githubusercontent.com/44055121/62928959-643b9c00-bdb1-11e9-9f89-f8de085d7aba.png)
![000_gt](https://user-images.githubusercontent.com/44055121/62928960-643b9c00-bdb1-11e9-98f0-982660d7b9a8.png)

Thanks in advance for your time.

**Comment by LMescheder** [comment]
Hi @simofoti,
thanks for reporting the issue - we will look into it! Maybe something was broken, when we prepared the public code release.
For reference: when we trained the model we achieved a training loss of about 4.
Sample visualization of prediction:
![002](https://user-images.githubusercontent.com/263228/63008013-03c85f80-be82-11e9-92d7-9a528d55cb1e.png)

**Comment by simofoti** [comment]
Hi @LMescheder,

Thanks for your quick answer! Your results looks much better for sure :) 
Yesterday I launched another training  with the learning rate and weight decay reported in their original paper. It reached epoch 40 with a loss again around 30, but this time seems to be still decreasing (really slowly). Hopefully it is just a matter of training for longer... I'll let you know if I have any success.

Thanks for giving me some reference.

**Comment by m-niemeyer** [comment]
Hi @simofoti,
thanks for providing feedback! 
We cloned this github repo yesterday night and started a new training for a pixel2mesh model with the config file provided in configs/img/pixel2mesh.yaml. These results indicate that training progresses as usual. For reference, below you can see the loss and the visualization for your example after one night of traning (~50k Iterations, Epoch 19).
Could it be that changed the pixel2mesh config or that something broke during the data downloading process?

Best of luck!

![loss](https://user-images.githubusercontent.com/22234124/63675930-2d6e7880-c7ea-11e9-9844-8a92c7140d7f.png)
![006](https://user-images.githubusercontent.com/22234124/63675939-32cbc300-c7ea-11e9-8ecc-aedb1745ee60.png)

**Comment by simofoti** [comment]
Hello,

Thanks for looking into it. I was able to make it work with my data and I stopped experimenting with ShapeNet. Now I have some time and I am trying to re-run the training on ShapeNet cloning again the repo and using the pre-processed data. I should be able to get some results tomorrow. I will let you know if I obtain the something. 

PS. Just to let you know... OccupancyNet worked properly

**Comment by simofoti** [comment]
Hello @m-niemeyer,

I have run the training over the whole weekend but I still don't get the same results as yours. 
These are the steps I followed:
- I cloned your repo again
- Since I already had the environment in place, I have just compiled the extension modules
- I executed the download script and it looks like it downloaded and unpacked the data automatically into the `data/ShapeNet` folder.
- I started the training with `python train.py config/img/pixel2mesh.yaml`

Here is what I get:

Training loss:
![train_loss](https://user-images.githubusercontent.com/44055121/64104381-096fe180-cd6c-11e9-8d7f-f4cb32650d17.png)

Validation losses:
![val_losses](https://user-images.githubusercontent.com/44055121/64104482-37552600-cd6c-11e9-8951-907d7107c6b5.png)

Prediction:
![009](https://user-images.githubusercontent.com/44055121/64104725-b21e4100-cd6c-11e9-98b7-2779ca304515.png)
GT:
![009_gt](https://user-images.githubusercontent.com/44055121/64104726-b21e4100-cd6c-11e9-8bdf-5842aff56043.png)

After the training I checked if something was different in the code (just to be sure that I didn't accidentally change something), but the repo is up-to-date with your origin/master branch (which seems to be the only one you released). 
Do you have any idea of what could possibly go wrong?

Thanks in advance.

**Comment by m-niemeyer** [comment]
Hi @simofoti ,

thanks for your detailed report. To check again that our provided code and data works, I followed the complete pipeline as indicated in the readme. That is, cloning the repo, creating the anaconda environment, building the extensions, and downloading the provided data. After one night of training, the loss and visualizations looks the same as before (see below), hence it worked fine for me.

![pix2mesh](https://user-images.githubusercontent.com/22234124/64471896-13705680-d157-11e9-807b-7010a38f5c49.png)

As it works fine for me, it is quite hard to "debug" what is going wrong in your case.
First, I would try to delete everything (including the anaconda environment and all cached packages) and follow the procedure again (you can also rename the environment to be sure). To do this, run `conda` env remove --name mesh_funcspace` and `conda clean --all`. You can rename the environment in the environment.yaml file. 

Good luck!

**Comment by LMescheder** [comment]
Problem seems to be resolved. Closing for now.

**Comment by LMescheder** [comment]
Could be related: #31

**Comment by YokkaBear** [comment]
> Hello @m-niemeyer,
> 
> I have run the training over the whole weekend but I still don't get the same results as yours.
> These are the steps I followed:
> ...
> The download script, as I said above, copied the data in the right folder. No errors were thrown by the script and for each object of each class in ShapeNet I have:
> 
> * 24 views,
> * the camera parameters (cameras.npz),
> * model.binvox,
> * pointcloud.npz,
> * points.npz.
> 
> Do you have any idea of what could possibly go wrong?
> 
> Thanks in advance.

Hello, @LMescheder , @simofoti and @m-niemeyer , I was trying to train pixel2mesh network out of the dataset constructed by my own. But after the data preprocessing according to this project, I found that for each object folder the camera parameters file (cameras.npz) does not exist. Could you please show me how to generate the camera parameters files (cameras.npz)? Thanks a lot

**Comment by zyz-1998** [comment]
> Hello,
> 
> First of all, thanks for your amazing work!
> I am currently trying to train your pixel2mesh implementation, but I am not able to obtain decent results and I was wondering if you changed something that is not tunable from its config file.
> 
> The code I am using doesn't have any modification and I downloaded your pre-processed data. After epoch 8 the loss plateaus around 30 and oscillates around that value at least until epoch 50 (then I stopped the training because didn't look like it was going to get better).
> 
> Here you can find the visualisation of a prediction and its GT at epoch 50.
> 
> ![000](https://user-images.githubusercontent.com/44055121/62928959-643b9c00-bdb1-11e9-9f89-f8de085d7aba.png)
> ![000_gt](https://user-images.githubusercontent.com/44055121/62928960-643b9c00-bdb1-11e9-98f0-982660d7b9a8.png)
> 
> Thanks in advance for your time.

hi, when I trying to train pixel2mesh implementation,  I have the following problems
Visualizing
Traceback (most recent call last):
  File "train.py", line 135, in <module>
    trainer.visualize(data_vis)
  File "/home/zyz/Project/occupancy_networks/im2mesh/pix2mesh/training.py", line 287, in visualize
    points_out = common.transform_points_back(pred_vertices_3, world_mat)
  File "/home/zyz/Project/occupancy_networks/im2mesh/common.py", line 228, in transform_points_back
    points_out = points_out @ b_inv(R.transpose(1, 2))
  File "/home/zyz/Project/occupancy_networks/im2mesh/common.py", line 209, in b_inv
    b_inv, _ = torch.gesv(eye, b_mat)
AttributeError: module 'torch' has no attribute 'gesv'

you have encountered this problem? I am looking forward to your help

**Comment by b7leung** [comment]
I have the same issues as the OP. Below are the training graphs, and an example of a final reconstructed mesh. I also tried training a model on the car class only, and saw similar results.

![SNAG-0000](https://user-images.githubusercontent.com/20059131/94351681-8c677800-0010-11eb-8a6a-27a13e8a8184.png)
![SNAG-0001](https://user-images.githubusercontent.com/20059131/94351691-b1f48180-0010-11eb-8937-8cd2d5d7f8c9.png)

**Comment by m-niemeyer** [comment]
Hi, the problem might be related to [this file ordering](https://github.com/autonomousvision/occupancy_networks/issues/92) issue. If this was the case, it should be fixed now. Thanks!
