### ISSUE TITLE
High frequency details

### ISSUE THREAD

**Issue by nicolasugrinovic** [autonomousvision/occupancy_networks#19]
Hi, thanks for the great work! I have trained the network generating data with the per-processing script and the end result looks good but it lacks details. Is there something I could/should do to improve the capture of details? Is there a parameter(s) to be changed in the per-processing step? Or  something of the like. Can MISE parameters can achieve more details? 
Thanks!

**Comment by LMescheder** [comment]
Hi @nicolasugrinovic,
your question is hard to answer without additional details about your goals / current status. Did you train on your own data? How do the results currently look like? 
To get a general sense what details you can expect, take a look at the pretrained models.
In general, longer training helps a lot to get more details. Moreover, it can be helpful to increase the number of upsampling steps for inference in your config file.
