### ISSUE TITLE
Scale of the model

### ISSUE THREAD

**Issue by rozentill** [autonomousvision/occupancy_networks#23]
Hi there,

Thanks for releasing the codes, it is an amazing work! I have tried to do shape completion on point cloud sampled from original shapenet models. It seems my data is not in the same scale as your data. Did you rescale the shapenet model? If so, can you provide the scale value? And for point cloud completion, does it matter a lot for the scale(I guess so) and the view? 

Thanks,
Ryan

**Comment by LMescheder** [comment]
Hi @rozentill,
yes, we rescaled all ShapeNet models to the unit bounding box (i.e. maximum length of bounding box is 1). Please see the paper + supplementary for details.

**Comment by rozentill** [comment]
Got it, it works much better now. Thanks!
