### ISSUE TITLE
What can I do if I only want to use the MISE part?

### ISSUE THREAD

**Issue by MayuOshima** [autonomousvision/occupancy_networks#3]
Hello, now I have some 3D object points(in .npy file) and I want to use the method MISE described in your paper to construct a mesh .
But how can I do that?

**Comment by LMescheder** [comment]
Hi @MayuOshima,
MISE is an algorithm to extract a mesh from a continuous occupancy function representation. I'm not sure what you want to achieve, but you can take a look at the [interface](https://github.com/autonomousvision/occupancy_networks/blob/master/im2mesh/utils/libmise/mise.pyx#L33). [Here](https://github.com/autonomousvision/occupancy_networks/blob/master/im2mesh/onet/generation.py#L111) you can see how it is used in practice. If you want to reconstruct from a point cloud instead, take a look at [configs/pointcloud/onet.yaml](https://github.com/autonomousvision/occupancy_networks/blob/master/configs/pointcloud/onet.yaml). Note however, that the pretrained model was trained on (aligned) ShapeNet. So, if you want to apply it to some different object category you might want to retrain / finetune the network.

**Comment by MayuOshima** [comment]
> Hi @MayuOshima,
> MISE is an algorithm to extract a mesh from a continuous occupancy function representation. I'm not sure what you want to achieve, but you can take a look at the [interface](https://github.com/autonomousvision/occupancy_networks/blob/master/im2mesh/utils/libmise/mise.pyx#L33). [Here](https://github.com/autonomousvision/occupancy_networks/blob/master/im2mesh/onet/generation.py#L111) you can see how it is used in practice. If you want to reconstruct from a point cloud instead, take a look at [configs/pointcloud/onet.yaml](https://github.com/autonomousvision/occupancy_networks/blob/master/configs/pointcloud/onet.yaml). Note however, that the pretrained model was trained on (aligned) ShapeNet. So, if you want to apply it to some different object category you might want to retrain / finetune the network.

Sorry for having not described my question clearly!

I mean, after I do the steps (mark voxels -> subdevide voxels -> evaluate network) x n and finally I reach the desired resolution and get the points(which are markd red in your paper), then I write these points in a .npy file. 

If I understand your method correctly, then I need apply the marching cubes algorithm and simplify the mesh and refine the mesh.  So I want to know where did you implement the whole steps - [(mark voxels -> subdevide voxels -> evaluate network) x n & marching cubes & simplify mesh & refine mesh]

As there are so many code in this project, I am getting a little confused about the implement.

**Comment by LMescheder** [comment]
> If I understand your method correctly, then I need apply the marching cubes algorithm and simplify the mesh and refine the mesh. So I want to know where did you implement the whole steps - [(mark voxels -> subdevide voxels -> evaluate network) x n & marching cubes & simplify mesh & refine mesh]

See [here](https://github.com/autonomousvision/occupancy_networks/blob/master/im2mesh/utils/libmise/mise.pyx#L33)  for the implementation of the inner loop of MISE. The outer loop is defined [here](https://github.com/autonomousvision/occupancy_networks/blob/master/im2mesh/onet/generation.py#L116). Finally, mesh extraction and refinement is done [here](https://github.com/autonomousvision/occupancy_networks/blob/master/im2mesh/onet/generation.py#L159), which calls [this method for refinement](https://github.com/autonomousvision/occupancy_networks/blob/master/im2mesh/onet/generation.py#L250) and [this function for simplification](https://github.com/autonomousvision/occupancy_networks/blob/master/im2mesh/utils/libsimplify/__init__.py#L7).

**Comment by MayuOshima** [comment]
> > If I understand your method correctly, then I need apply the marching cubes algorithm and simplify the mesh and refine the mesh. So I want to know where did you implement the whole steps - [(mark voxels -> subdevide voxels -> evaluate network) x n & marching cubes & simplify mesh & refine mesh]
> 
> See [here](https://github.com/autonomousvision/occupancy_networks/blob/master/im2mesh/utils/libmise/mise.pyx#L33) for the implementation of the inner loop of MISE. The outer loop is defined [here](https://github.com/autonomousvision/occupancy_networks/blob/master/im2mesh/onet/generation.py#L116). Finally, mesh extraction and refinement is done [here](https://github.com/autonomousvision/occupancy_networks/blob/master/im2mesh/onet/generation.py#L159), which calls [this method for refinement](https://github.com/autonomousvision/occupancy_networks/blob/master/im2mesh/onet/generation.py#L250) and [this function for simplification](https://github.com/autonomousvision/occupancy_networks/blob/master/im2mesh/utils/libsimplify/__init__.py#L7).

Thank you!!

**Comment by LMescheder** [comment]
You're welcome. Let me know if you have other questions.

**Comment by raphaelsulzer** [comment]
Hi, could you explain the 'threshold' parameter of the MISE code?
