### ISSUE TITLE
how can i train my own dataset?

### ISSUE THREAD

**Issue by itszash** [autonomousvision/occupancy_networks#32]
hi
i'm working on my university project and for that i have to train my own dataset and get 3d mesh files of my own dataset..my question is how can i do renderings and voxelizations of my own dataset as mentioned in 2nd point of building dataset? will really appreciate if you could reply my question.

**Comment by LMescheder** [comment]
Take a look at the [sample_mesh.py](https://github.com/autonomousvision/occupancy_networks/blob/master/scripts/sample_mesh.py) script. For renderings, we used [blender](https://github.com/panmari/stanford-shapenet-renderer).  Closing because it is a duplicate #30.
