### ISSUE TITLE
Which dataset type to use with custom dataset

### ISSUE THREAD

**Issue by jnyjxn** [autonomousvision/occupancy_networks#33]
Hello and thank you for this intriguing work!

I want to use my own custom dataset with this and just want to better understand the use cases for the different dataset types in the manifest -> ["data"]["dataset"].

I have a file structure like this:

`Dataset -> { Data_Item_1...Data_Item_N } -> { [Images x n], model.binvox, points.npz }`

from which I want to recover a mesh.

Should I use the ShapeNet dataset type or an Images dataset?

Many thanks for your insight!

**Comment by LMescheder** [comment]
You should usually the Shapes3D dataset type. The other datasets are only used for inference when you have already trained your model.

**Comment by jnyjxn** [comment]
Thank you for your quick response!

**Comment by gokceay** [comment]
> Hello and thank you for this intriguing work!
> 
> I want to use my own custom dataset with this and just want to better understand the use cases for the different dataset types in the manifest -> ["data"]["dataset"].
> 
> I have a file structure like this:
> 
> `Dataset -> { Data_Item_1...Data_Item_N } -> { [Images x n], model.binvox, points.npz }`
> 
> from which I want to recover a mesh.
> 
> Should I use the ShapeNet dataset type or an Images dataset?
> 
> Many thanks for your insight!

Hi @jnyjxn and @LMescheder thanks a lot for the custom dataset creation part debugging comments, it helped me a lot. I want to test my custom dataset and I created my 3D files .binvox, pointcloud.npz and point.npz, but I am not sure about images of the 3D data. What is the format of the images of the training for single image reconstruction (resnet18)? npz or png? For each 3D off watertight mesh I have one single png image. There is a get_r2n2_cameras.py but I could not clearly understand what is happening inside. 
Any help would be greatly appreciated. Thanks in advance

**Comment by TaroPlay** [comment]
> Hello and thank you for this intriguing work!
> 
> I want to use my own custom dataset with this and just want to better understand the use cases for the different dataset types in the manifest -> ["data"]["dataset"].
> 
> I have a file structure like this:
> 
> `Dataset -> { Data_Item_1...Data_Item_N } -> { [Images x n], model.binvox, points.npz }`
> 
> from which I want to recover a mesh.
> 
> Should I use the ShapeNet dataset type or an Images dataset?
> 
> Many thanks for your insight!
Halo,my friend.could you tell me how to generate the "{ [Images x n], model.binvox, points.npz }" files your own dataset.I have the difficulty with creating it.I could use some assistance, if you have a moment.
