### ISSUE TITLE
rendering & voxelizations

### ISSUE THREAD

**Issue by itszash** [autonomousvision/occupancy_networks#35]
from where can i download rendering & voxelizations choy et al. 2016 as mentioned in building Dataset?

**Comment by LMescheder** [comment]
Hi @itszash,
you can find the data [here](http://3d-r2n2.stanford.edu/) under "Datasets".
Best,
Lars

**Comment by LMescheder** [comment]
Fixed broken link in 77192fd6af03b1e5ae9f68032721622da4142e9d.
