### ISSUE TITLE
Own dataset training(unconditional models)

### ISSUE THREAD

**Issue by JUN-TSUZUKI** [autonomousvision/occupancy_networks#39]
I want to train using own dataset.
I execute sample_mesh.py, after I get watertight meshes.
So, I get pointclouds, voxels, occupancies.

After that, I execute train.py 
but i found following error.

Error occured when loading field points of model 〇〇
or
Error occured when loading field voxels of model 〇〇

I think that pointclouds and voxels can't be made exactly.
Please tell me anything solution.

(ShapeNet model can be train)

**Comment by JUN-TSUZUKI** [comment]
Maybe, when I execute sample_mesh.py I get points.npz which can't load occupancies.npz

**Comment by JUN-TSUZUKI** [comment]
sample_mesh.py does not execute exactly.
please tell me anything solution.
When you use any other dataset, didn't you have same problem?

**Comment by JUN-TSUZUKI** [comment]
I tried to use example 3d models(occupancy_networks/external/mesh-fusion/examples/chair_oooo.off)
However, I found same error.
Please tell me.

**Comment by zhaoyuanyuan2011** [comment]
Hi, just wondering have you solved the issue?
