### ISSUE TITLE
Pix2mesh wrong number of gt points in loader?

### ISSUE THREAD

**Issue by frankshen07** [autonomousvision/occupancy_networks#49]
Thank you for the great work! There is one part that I'm not clear about:

https://github.com/autonomousvision/occupancy_networks/blob/39b772e265e8cbb5a2aadf90541eff80417a2d37/im2mesh/pix2mesh/config.py#L82-L83

Should here be pointcloud_target_n? This might explain why pix2mesh was reported worse than AtlasNet, which contradicts the results I saw in other paper.

**Comment by m-niemeyer** [comment]
Hi @frankshen07 ,

Thanks a lot for your great observation! pointcloud_n doesn't make sense here as we don't use point cloud input - it specifies how many points are subsampled for calculating the Chamfer distance. 

We checked our internal repository and here we used the correct naming - hence we trained with the correct number of points. Still, thanks a lot for your observation!
