### ISSUE TITLE
about test data in paper

### ISSUE THREAD

**Issue by fashionguy** [autonomousvision/occupancy_networks#59]
The test images are the images used in the training phase? English is not my native language. My English is not very good. I am learning.
![image](https://user-images.githubusercontent.com/49114843/81476655-a19c5f80-9245-11ea-8cc7-8ae4169f93a8.png)

**Comment by AlexsaseXie** [comment]
To illustrate the representation power of this occ representation, both train set and test set are the same as the set of all 3D shapes from 'chair' class. That means to train OccNet on all 'chair' shapes, then examine how well OccNet can reconstruct the 3D shapes of chairs. For each 3D shape, the input for OccNet is a unique embedding vector. If the reconsturctions are well, the representation power should be strong.

**Comment by fashionguy** [comment]
You mean this images for test have been seen by the ONet?  
If so, how about the reconstruction power of the unseen image. Generalization ability for unfamiliar images.  
And do other papers do the same test way? For example, pixel2mesh, I remember that his test image is not seen.
![image](https://user-images.githubusercontent.com/49114843/82110381-975ff100-9770-11ea-8887-c70acf54259b.png)

**Comment by AlexsaseXie** [comment]
OccNet paper does have experiment on single-view image reconsturcion. Plz read the paper carefully XD. For single-view image reconstruction, there is train/val/test split. That means all single-view images and 3D shapes in test phase are unseen.

**Comment by fashionguy** [comment]
Thanks for your time.
