### ISSUE TITLE
How to use your own data set to train the model？

### ISSUE THREAD

**Issue by ChauncyFr** [autonomousvision/occupancy_networks#6]
How to use your own data set to train the model？

**Comment by LMescheder** [comment]
Hi @ChauncyFr ,
it would be great if you could be a bit more specific. Did you try to follow the instructions in the README? Where did you encounter issues?

**Comment by ChauncyFr** [comment]
> Hi @ChauncyFr ,
> it would be great if you could be a bit more specific. Did you try to follow the instructions in the README? Where did you encounter issues?

First of all, thank you for your reply. I want to use this method for 3D reconstruction of a regular box (for example, a courier box). I also collect photos of the box myself and want to train my own dataset to get the model.
I don't know how to pre-process and train my dataset. Can I train my own dataset (migration learning) based on your trained model and then get the model of my own dataset.

I look forward to your answer, thank you again!

**Comment by LMescheder** [comment]
Take a look at how we preprocess the data in `scripts/dataset_shapenet/build.sh` (also look at the corresponding section in the readme).
When you do this for your dataset, you should be able to apply our code to your data.

**Comment by ChauncyFr** [comment]
> Take a look at how we preprocess the data in `scripts/dataset_shapenet/build.sh` (also look at the corresponding section in the readme).
> When you do this for your dataset, you should be able to apply our code to your data.
Ok, I still have a question: Can you learn migration based on the model you are training, because my personal data set is relatively small, so I thought about whether I can continue to train my training model. Data sets for better results? For example, mask rcnn provides a pre-training model on the coco dataset. I only need a small amount of data to train my own data based on the pre-trained model, and finally get good results.

**Comment by LMescheder** [comment]
Closing, because it is duplicate #30.
