### ISSUE TITLE
chamfer l1 not consistent with paper number (order of magnitude difference)

### ISSUE THREAD

**Issue by hua-wu-que** [autonomousvision/occupancy_networks#61]
Hi,
I ran your pretrained model, but found the chamferL1 is order of magnitude lower than the number reported in the paper. for example, on shapenet chair, the number running your code is "0.020721574735611238", while in the paper it says: "0.228"

**Comment by m-niemeyer** [comment]
Hi @hua-wu-que , thanks for your interest in the project!

In our project, we we use 1/10 times the maximal edge length of the current object’s bounding box as unit 1. In practice, this means that we multiply the Chamfer-L1 values by a factor of 10. We describe this more detailed in [Section 4 - Metrics of the main paper](http://www.cvlibs.net/publications/Mescheder2019CVPR.pdf). Good luck with your research!
