### ISSUE TITLE
compile

### ISSUE THREAD

**Issue by xiayizhan2017** [autonomousvision/occupancy_networks#8]
I run python3 generate.py configs/demo.yaml
I get  import error : /im2mesh/dmc/ops/_cuda_ext.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN2atErrorCLENS_14SourceLocationERKSs

**Comment by andrewayres** [comment]
I'm getting something similar when running `python generate.py configs/demo.yaml`

```
ImportError: dlopen(/Users/{my username}/anaconda3/envs/mesh_funcspace/lib/python3.6/site-packages/torchvision/_C.cpython-36m-darwin.so, 2): Symbol not found: __ZN2at19NonVariableTypeMode10is_enabledEv
  Referenced from: /Users/{my username}/anaconda3/envs/mesh_funcspace/lib/python3.6/site-packages/torchvision/_C.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/{my username}/anaconda3/envs/mesh_funcspace/lib/python3.6/site-packages/torchvision/_C.cpython-36m-darwin.so
```

How do I fix this?

**Comment by JiamingSuen** [comment]
This is usually caused by environment version changes(e.g. python/pytorch version) after library compilation. You may try to delete the compiled binaries and recompile again.

**Comment by xiayizhan2017** [comment]
@JiamingSuen Thank you for your answer, but I don't understand the environmental version change.

**Comment by andrewayres** [comment]
could you say what version of PyTorch and CUDA this code works with? I've tried by deleting all build and cache files and compiling Pytorch (and torchvision) from source, and using both clang/clang++ and gcc/g++ on MacOS 10.13.6 with CUDA 10.0 but always get the above 'symbol not found' error when trying to run `generate.py`
