### ISSUE TITLE
Visualizing mesh and occupancy points

### ISSUE THREAD

**Issue by nicolasugrinovic** [autonomousvision/occupancy_networks#9]
Hi, thank you for sharing your code. 
Is there code in this repository to visualize a mesh along its predicted occupancy points? If not, could you point me how to get a visualization like this in your presentation video? 
![Selection_259](https://user-images.githubusercontent.com/25443240/60094234-c5e56f80-974b-11e9-830a-a3d399574bf8.png)

**Comment by LMescheder** [comment]
Hi @nicolasugrinovic,
we use blender for this. We have an internal tool (not open sourced) which simplifies the rendering steps a little bit, but if you know the blender python API this should also be fairly straightforward to achieve directly in blender.
